import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Play, ChevronRight } from 'lucide-react';
const Preloader = ({ onStart }) => {
    const [videoPlayed, setVideoPlayed] = useState(false);
    const handleVideoEnd = () => {
        setVideoPlayed(true);
    };
    return (_jsx("div", { className: "fixed inset-0 z-[100] flex flex-col items-center justify-center bg-black", children: _jsxs("div", { className: "w-full h-screen flex flex-col items-center justify-center relative", children: [_jsxs("div", { className: "absolute top-0 left-0 right-0 p-8 bg-gradient-to-b from-black via-black/70 to-transparent z-10", children: [_jsx("h1", { className: "text-4xl font-light tracking-wide text-white/90 text-center", children: "Lugares de Memoria" }), _jsx("p", { className: "text-xl text-white/60 text-center mt-2", children: "Centro Nacional de Memoria Hist\u00F3rica" })] }), _jsx("div", { className: "w-full h-full flex items-center justify-center relative", children: _jsx("div", { className: "w-full h-full relative overflow-hidden bg-black", children: _jsxs("div", { className: "absolute inset-0 flex items-center justify-center", children: [_jsx("img", { src: "/api/placeholder/1920/1080", alt: "Video Placeholder", className: "w-full h-full object-cover opacity-50" }), !videoPlayed && (_jsx("div", { className: "absolute inset-0 flex items-center justify-center bg-black/30 cursor-pointer", onClick: () => setVideoPlayed(true), children: _jsx("button", { className: "w-24 h-24 rounded-full bg-white/20 hover:bg-white/30 \n                    flex items-center justify-center transition-all duration-300 \n                    transform hover:scale-110", children: _jsx(Play, { className: "w-12 h-12 text-white" }) }) }))] }) }) }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black via-black/70 to-transparent", children: _jsx("div", { className: "container mx-auto p-8", children: videoPlayed ? (_jsx("div", { className: "flex flex-col items-center space-y-6", children: _jsxs("button", { onClick: onStart, className: "group px-8 py-4 rounded-full bg-white/10 hover:bg-white/20 \n                    backdrop-blur-sm flex items-center gap-3 transform hover:scale-105 \n                    transition-all duration-300", children: [_jsx("span", { className: "text-xl text-white", children: "Comenzar Recorrido" }), _jsx(ChevronRight, { className: "w-6 h-6 text-white group-hover:translate-x-2 transition-transform" })] }) })) : (_jsx("p", { className: "text-xl text-white/60 text-center", children: "Reproduce el video para continuar..." })) }) })] }) }));
};
export default Preloader;
