import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/NavComponents.tsx - Corrección para el panel de capas
// Reemplaza el componente SideButtons con esta versión actualizada
export const SideButtons = ({ activeLayers, onToggleLayer, onZoomIn, onZoomOut, onResetRotation }) => {
    const [showLayersPanel, setShowLayersPanel] = useState(false);
    return (_jsxs("div", { className: "fixed bottom-8 left-8 z-40 flex flex-col items-start gap-4", children: [_jsx(AnimatePresence, { children: showLayersPanel && (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: 20 }, className: "absolute bottom-16 left-full ml-4 bg-black/80 backdrop-blur-md rounded-lg p-4 \n                      border border-white/10 w-64 shadow-lg", style: { zIndex: 45 }, children: [_jsx("h3", { className: "text-white font-medium text-sm mb-3", children: "Capas Ambientales" }), _jsx("div", { className: "space-y-2", children: [
                                { id: 'deforestation', name: 'Deforestación', color: '#FF4444' },
                                { id: 'mining', name: 'Minería Ilegal', color: '#FF8C00' },
                                { id: 'erosion', name: 'Erosión del Suelo', color: '#2196F3' }
                            ].map(layer => {
                                const isActive = activeLayers.includes(layer.id);
                                return (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-14 h-6 relative rounded-full transition-colors ${isActive ? 'bg-white/20' : 'bg-black/40'}`, onClick: () => onToggleLayer(layer.id), role: "checkbox", "aria-checked": isActive, tabIndex: 0, children: _jsx("div", { className: `absolute top-1 w-4 h-4 rounded-full transition-all ${isActive
                                                    ? 'right-1'
                                                    : 'left-1 bg-white/40'}`, style: { backgroundColor: isActive ? layer.color : 'rgba(255,255,255,0.4)' } }) }), _jsx("span", { className: "text-white text-sm", children: layer.name })] }, layer.id));
                            }) })] })) }), _jsxs("button", { onClick: () => setShowLayersPanel(!showLayersPanel), className: "bg-black/70 backdrop-blur-md rounded-full px-4 py-2.5 \n                  flex items-center gap-2 shadow-lg text-white\n                  border border-white/10 transition-all hover:bg-black/80", children: [_jsx(Layers, { size: 18 }), _jsx("span", { children: "Capas" })] }), _jsxs("div", { className: "flex flex-col gap-3", children: [_jsx("button", { onClick: onZoomIn, className: "bg-black/70 backdrop-blur-md rounded-full p-2.5 \n                    shadow-lg text-white border border-white/10 \n                    hover:bg-black/80 transition-all", title: "Acercar", children: _jsx(ZoomIn, { size: 18 }) }), _jsx("button", { onClick: onZoomOut, className: "bg-black/70 backdrop-blur-md rounded-full p-2.5 \n                    shadow-lg text-white border border-white/10 \n                    hover:bg-black/80 transition-all", title: "Alejar", children: _jsx(ZoomOut, { size: 18 }) }), _jsx("button", { onClick: onResetRotation, className: "bg-black/70 backdrop-blur-md rounded-full p-2.5 \n                    shadow-lg text-white border border-white/10 \n                    hover:bg-black/80 transition-all", title: "Restablecer rotaci\u00F3n", children: _jsx(Compass, { size: 18 }) })] })] }));
};
