import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/TourSelector.tsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Map, Shield, Tent, Mountain, Leaf, Heart, X, ChevronRight, Users, Landmark, Building, Clock, ArrowRight, Eye } from 'lucide-react';
import { thematicTours } from '../utils/demoState';
const iconMap = {
    'Map': _jsx(Map, { strokeWidth: 1.5 }),
    'Shield': _jsx(Shield, { strokeWidth: 1.5 }),
    'Tent': _jsx(Tent, { strokeWidth: 1.5 }),
    'Mountain': _jsx(Mountain, { strokeWidth: 1.5 }),
    'Leaf': _jsx(Leaf, { strokeWidth: 1.5 }),
    'Heart': _jsx(Heart, { strokeWidth: 1.5 }),
    'Users': _jsx(Users, { strokeWidth: 1.5 }),
    'Landmark': _jsx(Landmark, { strokeWidth: 1.5 }),
    'Building': _jsx(Building, { strokeWidth: 1.5 })
};
const TourSelector = ({ isOpen, onClose, onSelectTour }) => {
    const [selectedTourId, setSelectedTourId] = useState(null);
    const [hoverIndex, setHoverIndex] = useState(null);
    if (!isOpen)
        return null;
    const selectedTour = selectedTourId ? thematicTours.find(tour => tour.id === selectedTourId) : null;
    return (_jsxs(motion.div, { className: "fixed inset-0 z-50 flex items-center justify-center", initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, transition: { duration: 0.3 }, children: [_jsx("div", { className: "absolute inset-0 bg-black/60 backdrop-blur-sm", onClick: onClose }), _jsxs(motion.div, { className: "relative w-full max-w-4xl mx-4 h-[75vh] max-h-[700px] flex flex-col md:flex-row overflow-hidden", initial: { scale: 0.9, y: 20 }, animate: { scale: 1, y: 0 }, exit: { scale: 0.9, y: 20 }, transition: { type: 'spring', damping: 25, stiffness: 300 }, children: [_jsxs(motion.div, { className: "w-full md:w-1/2 bg-gray-500/30 backdrop-filter backdrop-blur-xl rounded-t-2xl md:rounded-l-2xl md:rounded-tr-none border-l border-t border-white/10 shadow-2xl overflow-y-auto", style: { height: selectedTourId ? '100%' : 'auto' }, children: [_jsxs("div", { className: "sticky top-0 z-10 bg-gray-500/20 backdrop-blur-md border-b border-white/10 px-6 py-4 flex justify-between items-center", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-xl text-white font-light tracking-wide", children: "Recorridos Tem\u00E1ticos" }), _jsx("p", { className: "text-white/50 text-xs mt-1", children: "Explora Colombia a trav\u00E9s de diferentes perspectivas" })] }), _jsx("button", { onClick: onClose, className: "w-8 h-8 rounded-full bg-white/5 hover:bg-white/15 border border-white/10 transition-colors flex items-center justify-center", children: _jsx(X, { size: 16, className: "text-white" }) })] }), _jsxs("div", { className: "p-4", children: [_jsx("div", { className: "grid grid-cols-1 gap-3", children: thematicTours.map((tour, index) => (_jsxs(motion.div, { className: `relative overflow-hidden rounded-xl cursor-pointer group
                              ${selectedTourId === tour.id ? 'ring-2 ring-white/20' : 'hover:ring-1 hover:ring-white/10'}`, initial: { opacity: 0, y: 10 }, animate: {
                                                opacity: 1,
                                                y: 0,
                                                scale: selectedTourId && selectedTourId !== tour.id ? 0.97 : 1
                                            }, transition: {
                                                duration: 0.4,
                                                delay: index * 0.05,
                                                ease: [0.16, 1, 0.3, 1]
                                            }, onMouseEnter: () => setHoverIndex(index), onMouseLeave: () => setHoverIndex(null), onClick: () => setSelectedTourId(tour.id), children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-black/70 via-black/50 to-black/80 z-0" }), _jsx("div", { className: "absolute inset-0 opacity-20 z-0", style: {
                                                        background: `radial-gradient(circle at 30% 50%, ${tour.color}30, transparent 70%)`,
                                                    } }), _jsxs("div", { className: "relative z-10 p-5 flex flex-col md:flex-row gap-4 items-start md:items-center", children: [_jsx(motion.div, { className: "flex-shrink-0 w-12 h-12 rounded-full flex items-center justify-center", style: {
                                                                background: `linear-gradient(135deg, ${tour.color}60, ${tour.color}20)`,
                                                                boxShadow: `0 0 20px ${tour.color}40`
                                                            }, animate: {
                                                                scale: hoverIndex === index ? 1.05 : 1,
                                                                rotate: hoverIndex === index ? 5 : 0
                                                            }, transition: { type: "spring", stiffness: 400, damping: 10 }, children: _jsx("div", { className: "text-white w-6 h-6", children: iconMap[tour.icon] }) }), _jsxs("div", { className: "flex-1 flex flex-col md:flex-row md:items-center justify-between w-full", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-white text-lg font-light", children: tour.title }), _jsx("p", { className: "text-white/60 text-xs line-clamp-1 mt-1 max-w-md", children: tour.description })] }), _jsxs("div", { className: "flex items-center mt-2 md:mt-0 md:ml-4", children: [_jsxs("div", { className: "flex items-center mr-5 text-white/50 text-xs", children: [_jsx(Clock, { size: 14, className: "mr-1" }), tour.duration] }), _jsx(motion.div, { className: "w-8 h-8 rounded-full bg-white/5 flex items-center justify-center", animate: {
                                                                                x: hoverIndex === index ? 5 : 0,
                                                                                backgroundColor: hoverIndex === index
                                                                                    ? `rgba(255,255,255,0.2)`
                                                                                    : `rgba(255,255,255,0.05)`
                                                                            }, children: _jsx(ChevronRight, { size: 16, className: "text-white" }) })] })] })] })] }, tour.id))) }), _jsxs(motion.div, { className: "mt-4 rounded-xl overflow-hidden relative", initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.4 }, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-green-900/40 to-emerald-900/30 z-0" }), _jsxs("div", { className: "relative z-10 p-4 flex items-start gap-3", children: [_jsx("div", { className: "p-2 rounded-full bg-green-500/20 text-green-400", children: _jsx(Leaf, { size: 16, strokeWidth: 1.5 }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "text-green-300 text-sm font-medium mb-1", children: "Impacto ambiental" }), _jsx("p", { className: "text-green-100/70 text-xs leading-relaxed", children: "Explora c\u00F3mo el conflicto armado ha afectado los ecosistemas y recursos naturales de Colombia. Activa las capas ambientales para visualizar \u00E1reas afectadas." })] })] })] })] })] }), _jsx(AnimatePresence, { children: selectedTour && (_jsx(motion.div, { className: "w-full md:w-1/2 bg-gray-500/30 backdrop-filter backdrop-blur-xl rounded-b-2xl md:rounded-r-2xl md:rounded-bl-none border-r border-b border-t md:border-t-0 border-white/10 shadow-2xl overflow-y-auto", initial: { opacity: 0, x: 20 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: 20 }, transition: { type: "spring", stiffness: 300, damping: 25 }, children: _jsxs("div", { className: "p-6 bg-gray-500/20", children: [_jsxs("div", { className: "w-full h-48 rounded-xl mb-5 overflow-hidden relative bg-center bg-cover", style: {
                                            backgroundImage: `url(https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?q=80&w=1000)`, // Placeholder - Reemplazar con imagen real
                                            boxShadow: `inset 0 0 100px 20px rgba(0,0,0,0.8)`
                                        }, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-gray-900/80 via-gray-900/40 to-transparent" }), _jsxs("div", { className: "absolute bottom-0 left-0 right-0 p-4", children: [_jsx(motion.div, { className: "inline-block py-1 px-3 rounded-full text-xs", style: {
                                                            backgroundColor: `${selectedTour.color}35`,
                                                            color: `${selectedTour.color}`
                                                        }, initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2 }, children: selectedTour.id === 'general' ? 'Destacado' : 'Recorrido Temático' }), _jsx(motion.h2, { className: "text-white text-2xl font-light mt-2", initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.3 }, children: selectedTour.title })] })] }), _jsx(motion.p, { className: "text-white/80 text-sm leading-relaxed mb-6", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.4 }, children: selectedTour.description }), _jsxs("div", { className: "mb-5", children: [_jsx("h3", { className: "text-white/90 text-sm font-medium mb-3", children: "Detalles del recorrido" }), _jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs("div", { className: "bg-white/5 rounded-lg p-3 flex items-center", children: [_jsx(Clock, { className: "text-white/60 w-4 h-4 mr-2" }), _jsxs("div", { children: [_jsx("div", { className: "text-white/70 text-xs", children: "Duraci\u00F3n" }), _jsx("div", { className: "text-white text-sm", children: selectedTour.duration })] })] }), _jsxs("div", { className: "bg-white/5 rounded-lg p-3 flex items-center", children: [_jsx(Eye, { className: "text-white/60 w-4 h-4 mr-2" }), _jsxs("div", { children: [_jsx("div", { className: "text-white/70 text-xs", children: "Lugares" }), _jsxs("div", { className: "text-white text-sm", children: [selectedTour.locations.length, " sitios"] })] })] })] })] }), _jsxs("div", { className: "mb-6", children: [_jsx("h3", { className: "text-white/90 text-sm font-medium mb-3", children: "Lugares que visitar\u00E1s" }), _jsx("div", { className: "space-y-2 max-h-40 overflow-y-auto pr-2 custom-scrollbar", children: selectedTour.locations.map((locationId, index) => (_jsx(motion.div, { className: "bg-white/5 hover:bg-white/10 rounded-lg p-3 flex items-center justify-between transition-colors", initial: { opacity: 0, y: 5 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.1 * index }, children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "w-6 h-6 rounded-full flex items-center justify-center mr-3 text-xs font-medium", style: { backgroundColor: `${selectedTour.color}35`, color: selectedTour.color }, children: index + 1 }), _jsx("span", { className: "text-white/90 text-sm", children: locationId.split('_').join(' ') })] }) }, locationId))) })] }), _jsxs(motion.button, { className: "w-full py-3 px-4 rounded-lg flex items-center justify-center text-white font-medium", style: {
                                            background: `linear-gradient(135deg, ${selectedTour.color}, ${selectedTour.color}90)`,
                                            boxShadow: `0 4px 12px ${selectedTour.color}30`
                                        }, whileHover: { scale: 1.02, boxShadow: `0 6px 20px ${selectedTour.color}50` }, whileTap: { scale: 0.98 }, onClick: () => onSelectTour(selectedTour.id), children: [_jsx("span", { children: "Iniciar recorrido" }), _jsx(ArrowRight, { className: "ml-2 w-4 h-4" })] })] }) })) })] })] }));
};
export default TourSelector;
